"""Session-local generated media previews with bounded streaming validation."""

from __future__ import annotations

import hashlib
import io
import math
import os
from dataclasses import dataclass
from pathlib import Path
import re
import secrets
import shutil
import threading
from types import MappingProxyType
from typing import Any, BinaryIO, Mapping

from Auvra.project.assets import sniff_mime


_CHUNK = 1024 * 1024
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_JOB_ID = re.compile(r"^job-[A-Za-z0-9_-]{16,128}$")
_PROVIDER_ID = re.compile(r"^[a-z][a-z0-9._-]{0,63}$")
_SUPPORTED_IMAGES = frozenset({"image/png", "image/jpeg", "image/webp"})
_PROVENANCE_FIELDS = frozenset({
    "providerId", "modelId", "modelVersion", "jobId", "createdAt",
    "routeOrigin", "routeConsent", "promptSha256", "settingsSha256",
    "inputAssetIds", "seed", "costMicroUsd",
})


class PreviewError(RuntimeError):
    """Generated preview failed a local integrity or lifecycle check."""


@dataclass(frozen=True, slots=True)
class PreviewRecord:
    job_id: str
    asset_id: str
    size: int
    mime: str
    width: int
    height: int
    provenance: Mapping[str, Any]


class PreviewStore:
    """Own validated generated bytes until the user commits or discards them."""

    def __init__(self, parent: Path, *, max_size: int = 128 * 1024 * 1024) -> None:
        if not isinstance(max_size, int) or not 1 <= max_size <= 2 * 1024**3:
            raise ValueError("preview size bound is invalid")
        parent = Path(parent).expanduser().absolute()
        parent.mkdir(parents=True, exist_ok=True)
        self._parent = parent.resolve()
        self._root = self._parent / ("preview-session-" + secrets.token_urlsafe(18))
        self._root.mkdir(mode=0o700)
        self._max_size = max_size
        self._lock = threading.RLock()
        self._records: dict[tuple[str, str], PreviewRecord] = {}
        self._closed = False

    def ingest(
        self,
        job_id: str,
        stream: BinaryIO,
        *,
        declared_mime: str | None = None,
        expected_hash: str | None = None,
        provenance: Mapping[str, Any] | None = None,
    ) -> PreviewRecord:
        self._validate_job(job_id)
        if expected_hash is not None and not _SHA256.fullmatch(expected_hash):
            raise PreviewError("generated media hash is invalid")
        normalized_mime = str(declared_mime or "").split(";", 1)[0].strip().lower()
        if normalized_mime and normalized_mime not in _SUPPORTED_IMAGES:
            raise PreviewError("generated media type is unsupported")
        metadata = _safe_provenance(provenance or {}, job_id=job_id)
        with self._lock:
            self._require_open()
            temporary = self._root / ("incoming-" + secrets.token_urlsafe(18))

        digest = hashlib.sha256()
        size = 0
        prefix = bytearray()
        try:
            with temporary.open("xb") as output:
                while True:
                    chunk = stream.read(_CHUNK)
                    if not chunk:
                        break
                    if not isinstance(chunk, (bytes, bytearray, memoryview)) or len(chunk) > _CHUNK:
                        raise PreviewError("generated media stream is invalid")
                    block = bytes(chunk)
                    size += len(block)
                    if size > self._max_size:
                        raise PreviewError("generated media exceeds the preview size limit")
                    if len(prefix) < 64:
                        prefix.extend(block[: 64 - len(prefix)])
                    digest.update(block)
                    output.write(block)
                output.flush()
                os.fsync(output.fileno())
            if size == 0:
                raise PreviewError("generated media is empty")
            actual_hash = digest.hexdigest()
            if expected_hash is not None and not secrets.compare_digest(actual_hash, expected_hash):
                raise PreviewError("generated media hash does not match")
            actual_mime = sniff_mime(bytes(prefix))
            if actual_mime not in _SUPPORTED_IMAGES:
                raise PreviewError("generated media content is unsupported")
            if normalized_mime and normalized_mime != actual_mime:
                raise PreviewError("generated media type does not match its content")
            width, height = _image_dimensions(temporary, actual_mime)
            if not 1 <= width <= 65536 or not 1 <= height <= 65536:
                raise PreviewError("generated image dimensions are invalid")
            destination = self._root / (actual_hash + ".preview")
            with self._lock:
                self._require_open()
                if destination.exists():
                    temporary.unlink(missing_ok=True)
                else:
                    os.replace(temporary, destination)
                record = PreviewRecord(
                    job_id, actual_hash, size, actual_mime, width, height, metadata
                )
                self._records[(job_id, actual_hash)] = record
                return record
        except Exception:
            temporary.unlink(missing_ok=True)
            raise

    def get(self, job_id: str, asset_id: str) -> PreviewRecord:
        self._validate_job(job_id)
        self._validate_asset(asset_id)
        with self._lock:
            self._require_open()
            try:
                return self._records[(job_id, asset_id)]
            except KeyError as exc:
                raise PreviewError("generated preview is unavailable") from exc

    def find(self, asset_id: str) -> PreviewRecord:
        """Resolve a session preview by content identity for local asset tickets."""

        self._validate_asset(asset_id)
        with self._lock:
            self._require_open()
            matches = [record for (_, identity), record in self._records.items() if identity == asset_id]
            if not matches:
                raise PreviewError("generated preview is unavailable")
            return matches[0]

    def open(self, asset_id: str) -> BinaryIO:
        record = self.find(asset_id)
        path = self._path(record.asset_id)
        with self._lock:
            self._require_open()
            _reject_reparse(path)
            try:
                stream = path.open("rb")
            except OSError as exc:
                raise PreviewError("generated preview failed integrity validation") from exc
        try:
            if os.fstat(stream.fileno()).st_size != record.size:
                raise PreviewError("generated preview failed integrity validation")
            digest = hashlib.sha256()
            for block in iter(lambda: stream.read(_CHUNK), b""):
                digest.update(block)
            if not secrets.compare_digest(digest.hexdigest(), record.asset_id):
                raise PreviewError("generated preview failed integrity validation")
            stream.seek(0)
            return stream
        except Exception:
            stream.close()
            raise

    def discard(self, job_id: str, asset_id: str) -> None:
        self.get(job_id, asset_id)
        with self._lock:
            self._records.pop((job_id, asset_id), None)
            if not any(identity == asset_id for _, identity in self._records):
                self._path(asset_id).unlink(missing_ok=True)

    def close(self) -> None:
        with self._lock:
            if self._closed:
                return
            self._closed = True
            self._records.clear()
        _reject_reparse(self._root)
        resolved = self._root.resolve(strict=False)
        if resolved.parent != self._parent or not resolved.name.startswith("preview-session-"):
            raise PreviewError("preview cleanup boundary is invalid")
        shutil.rmtree(resolved, ignore_errors=False)

    def _path(self, asset_id: str) -> Path:
        self._validate_asset(asset_id)
        return self._root / (asset_id + ".preview")

    def _require_open(self) -> None:
        if self._closed:
            raise PreviewError("preview store is closed")

    @staticmethod
    def _validate_job(job_id: str) -> None:
        if not isinstance(job_id, str) or not _JOB_ID.fullmatch(job_id):
            raise PreviewError("provider job identity is invalid")

    @staticmethod
    def _validate_asset(asset_id: str) -> None:
        if not isinstance(asset_id, str) or not _SHA256.fullmatch(asset_id):
            raise PreviewError("generated asset identity is invalid")


def _safe_provenance(value: Mapping[str, Any], *, job_id: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping) or len(value) > 24:
        raise PreviewError("generated provenance is invalid")
    if any(not isinstance(key, str) or key not in _PROVENANCE_FIELDS for key in value):
        raise PreviewError("generated provenance contains an unsupported field")
    result: dict[str, Any] = {}
    for key, child in value.items():
        if key == "providerId":
            if not isinstance(child, str) or not _PROVIDER_ID.fullmatch(child):
                raise PreviewError("generated provider identity is invalid")
        elif key in {"modelId", "modelVersion"}:
            if not isinstance(child, str) or not 1 <= len(child) <= 192 or any(
                marker in child for marker in ("\x00", "\n", "\r", "\\")
            ):
                raise PreviewError("generated model identity is invalid")
        elif key == "jobId":
            if child != job_id:
                raise PreviewError("generated provenance job does not match")
        elif key in {"promptSha256", "settingsSha256"}:
            if not isinstance(child, str) or not _SHA256.fullmatch(child):
                raise PreviewError("generated provenance hash is invalid")
        elif key == "inputAssetIds":
            if not isinstance(child, (list, tuple)) or len(child) > 16:
                raise PreviewError("generated input assets are invalid")
            normalized = tuple(child)
            if len(set(normalized)) != len(normalized) or any(
                not isinstance(asset_id, str) or not _SHA256.fullmatch(asset_id)
                for asset_id in normalized
            ):
                raise PreviewError("generated input assets are invalid")
            child = normalized
        elif key == "routeOrigin":
            if child not in {"cloud", "local"}:
                raise PreviewError("generated route origin is invalid")
        elif key == "routeConsent":
            if child not in {"explicit", "fallback"}:
                raise PreviewError("generated route consent is invalid")
        elif key == "createdAt":
            if not isinstance(child, (int, float)) or isinstance(child, bool) or not math.isfinite(child) or child < 0:
                raise PreviewError("generated timestamp is invalid")
        elif key in {"seed", "costMicroUsd"}:
            if not isinstance(child, int) or isinstance(child, bool) or not 0 <= child <= 1_000_000_000_000:
                raise PreviewError("generated numeric provenance is invalid")
        result[key] = child
    return MappingProxyType(result)


def _image_dimensions(path: Path, mime: str) -> tuple[int, int]:
    with path.open("rb") as stream:
        if mime == "image/png":
            header = stream.read(24)
            if len(header) != 24 or header[12:16] != b"IHDR":
                raise PreviewError("generated PNG is malformed")
            return int.from_bytes(header[16:20], "big"), int.from_bytes(header[20:24], "big")
        if mime == "image/webp":
            header = stream.read(30)
            if len(header) < 25 or header[:4] != b"RIFF" or header[8:12] != b"WEBP":
                raise PreviewError("generated WebP is malformed")
            kind = header[12:16]
            if kind == b"VP8X" and len(header) >= 30:
                return 1 + int.from_bytes(header[24:27], "little"), 1 + int.from_bytes(header[27:30], "little")
            if kind == b"VP8 " and len(header) >= 30 and header[23:26] == b"\x9d\x01\x2a":
                return int.from_bytes(header[26:28], "little") & 0x3FFF, int.from_bytes(header[28:30], "little") & 0x3FFF
            if kind == b"VP8L" and header[20] == 0x2F:
                bits = int.from_bytes(header[21:25], "little")
                return 1 + (bits & 0x3FFF), 1 + ((bits >> 14) & 0x3FFF)
            raise PreviewError("generated WebP dimensions are unavailable")
        if mime == "image/jpeg":
            if stream.read(2) != b"\xff\xd8":
                raise PreviewError("generated JPEG is malformed")
            while True:
                marker_start = stream.read(1)
                if not marker_start:
                    break
                if marker_start != b"\xff":
                    continue
                marker = stream.read(1)
                while marker == b"\xff":
                    marker = stream.read(1)
                if not marker or marker in {b"\xd8", b"\xd9"}:
                    continue
                length_bytes = stream.read(2)
                if len(length_bytes) != 2:
                    break
                length = int.from_bytes(length_bytes, "big")
                if length < 2 or length > 65535:
                    break
                if marker[0] in {0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}:
                    data = stream.read(5)
                    if len(data) != 5:
                        break
                    return int.from_bytes(data[3:5], "big"), int.from_bytes(data[1:3], "big")
                stream.seek(length - 2, io.SEEK_CUR)
            raise PreviewError("generated JPEG dimensions are unavailable")
    raise PreviewError("generated image type is unsupported")


def _reject_reparse(path: Path) -> None:
    """Fail closed if a preview path was replaced by a link or junction."""

    try:
        if path.is_symlink() or (getattr(path.lstat(), "st_file_attributes", 0) & 0x400):
            raise PreviewError("generated preview path is not trusted")
    except FileNotFoundError as exc:
        raise PreviewError("generated preview is unavailable") from exc
